replicaCount: 1
image:
  repository: mysql
  tag: "lts"
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 3306
resources:
env:
  - name: MYSQL_DATABASE
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: name
  - name: MYSQL_USER
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: user
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: password
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: root_password
volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-volume-claim
volumeMounts:
  - name: mysql-storage
    mountPath: /var/lib/mysql