---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJaR1Z1TG5Sb1lXazZaMnh3WVhRdFJXbGZaM2REZVc5WExVeEJVVTF1U25oS1FYRT0iCgkJfQoJfQp9